### ISSUE TITLE
How upgrades are handled in this image?

### ISSUE THREAD

**Issue by navossoc** [roundcube/roundcubemail-docker#178]
Hi, I would like to know how upgrades are being handled.

Are they automatic?
I mean, let's say I am using 1.5.2 and them 1.5.3 comes out.

What is the procedure?
Pull the last image and bring it up or do I need to remove any old files on the mount bind `/var/www/html`?

Thanks.

PS: Also, we are missing the tag for `1.5.2` on this repository.

**Comment by thomascube** [comment]
Yes, upgrading should be as simple as pulling a new image. The entrypoint script will update existing files in `/var/www/html` if mounted.

The 1.5.2 version is available via [Docker Hub](https://hub.docker.com/r/roundcube/roundcubemail/tags?page=1&name=1.5.2).

**Comment by navossoc** [comment]
> Yes, upgrading should be as simple as pulling a new image. The entrypoint script will update existing files in `/var/www/html` if mounted.
> 
> The 1.5.2 version is available via [Docker Hub](https://hub.docker.com/r/roundcube/roundcubemail/tags?page=1&name=1.5.2).

I really mean on this git repository:
https://github.com/roundcube/roundcubemail-docker/tags

There is no 1.5.2.

What about the plugins? I saw we can install them using composer now...
Also they can change the config.php to load the added plugin if you want.

But the update there is still manual right?
Otherwise I  guess I should create a Dockerfile and run composer when building it or at the entrypoint...

Thanks.

**Comment by thomascube** [comment]
Plugins can be installed via composer as [described in the README](/roundcube/roundcubemail-docker#installing-roundcube-plugins). If you have a volume attached to `/var/www/html` the installed plugins and the altered config fill persist and pulling a new version will update that directory (without updating the plugins).

In order to have everything self-contained we recommend to [build your own image](/roundcube/roundcubemail-docker#building-a-docker-image) based on our releases.
