### ISSUE TITLE
How does this image handle updates?

### ISSUE THREAD

**Issue by marcelklehr** [roundcube/roundcubemail-docker#58]
Hey,

I was wondering whether this image offers any way to update roundcube?

**Comment by thomascube** [comment]
New images (tags) are created and pushed to docker hub for Roundcube releases.

**Comment by marcelklehr** [comment]
So, when I pull the new release roundcube will be updated automatically, or do I have to do anything else?

**Comment by thomascube** [comment]
You just pull the new docker image, that's all.

**Comment by madmath03** [comment]
@marcelklehr The source code of RoundCube will be updated automatically when pull a new docker image, but if there are any database updates, you will have to perform them manually. Is that what you had in mind ?

@thomascube Do you think we could execute [updatedb.sh](https://github.com/roundcube/roundcubemail/blob/master/bin/updatedb.sh) through the entrypoint to automatically update the DB ?

**Comment by thomascube** [comment]
@madmath03 `updatedb.sh` is executed when `config/config.inc.php` is created. That is IMO the case when you update and restart a docker container. In case the document root is stored on a mounted volume, upgrading needs to be done manually anyway.

**Comment by madmath03** [comment]
@thomascube Well, that's what I was wondering when reading this issue : shouldn't we add a mechanism to trigger the update no matter if the document root is mounted on a volume or not ?

It does not have to be the default behavior, we could add a variable env to trigger this (`ROUNDCUBEMAIL_DB_UPDATE=TRUE`), and then only execute the update if the sources at `/usr/src/roundcubemail` are more recent than the document root (compare CHANGELOG maybe).
What do you think ? Bad idea ?

**Comment by marcelklehr** [comment]
This is what I had in mind, indeed. Nextcloud's docker image does something similar which is quite satisfying.

**Comment by thomascube** [comment]
@madmath03 Such a mechanism could indeed make sense. However, that should include updating the Roundcube sources as well if they're on a shared volume. Otherwise updating the image has no effect and does not load the contained version of Roundcube. The entire update process can be done by calling `/usr/src/roundcubemail/bin/installto.sh .` which already includes a call to `updatedb.sh`. Anyway, the use of a shared volume as document root is not encouraged and not documented. Not sure if that's worth the effort.

**Comment by ckristo** [comment]
> @madmath03 ... Anyway, the use of a shared volume as document root is not encouraged and not documented. Not sure if that's worth the effort.

I guess this does not apply for the FPM image, since you need to share the “source” - specifically the static assets like CSS, JS or image files - with some web server residing in a different container. As far as I know, the Docker way of achieving that is using (named) volumes and mount them in both containers. Or do I miss something here?
